Print error message instead of panic on unrecognized option
Before:
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnrecognizedOption("version")', src/main.rs:126:46
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    Aborted

After:
    pipr: Unrecognized option: 'version'